@echo off
REM PM-AUTONOMOUS-30D: install per-user logon autostart for the Polymarket bot.
REM
REM IMPORTANT design note (2026-04-30):
REM   We attempted Task Scheduler /SC ONLOGON first. Windows denies user-level
REM   creation of ONLOGON tasks ("Acesso negado") even with /RU and /IT — it
REM   requires admin/UAC. To stay autonomous (no UAC), we instead drop a
REM   wrapper .bat into the user's Startup folder, which runs at login under
REM   the user account with no elevation prompt.
REM
REM   The wrapper (PolymarketAutoStart.bat) calls the real start-bot.bat via
REM   ABSOLUTE PATH (the prior Startup copy used %~dp0\.. which resolved to
REM   the Startup folder, not the bot — that was broken).
REM
REM Idempotent — overwrites any existing wrapper.
REM Removes legacy broken copy "PolymarketBot.bat" if found.

setlocal EnableDelayedExpansion
set "TASKNAME=PolymarketBotAutoStart"
set "SCRIPTDIR=%~dp0"

REM Resolve APPROOT (parent of scripts/)
pushd "%SCRIPTDIR%.."
set "APPROOT=%CD%"
popd
set "REAL_STARTBAT=%APPROOT%\scripts\start-bot.bat"

echo Installing autostart: %TASKNAME%
echo Bot start script: %REAL_STARTBAT%

if not exist "%REAL_STARTBAT%" (
    echo ERROR: %REAL_STARTBAT% not found.
    exit /b 1
)

REM Locate Startup folder for current user (per-user, no UAC)
for /f "tokens=*" %%i in ('powershell -NoProfile -Command "[Environment]::GetFolderPath('Startup')"') do set "STARTUP=%%i"

if not exist "%STARTUP%" (
    echo ERROR: Startup folder not found at "%STARTUP%"
    exit /b 1
)

set "WRAPPER=%STARTUP%\PolymarketAutoStart.bat"
set "LEGACY=%STARTUP%\PolymarketBot.bat"

REM Remove legacy broken copy if present
if exist "%LEGACY%" (
    echo Removing legacy broken wrapper: %LEGACY%
    del /F "%LEGACY%"
)

REM Write the wrapper (absolute paths only).
REM Use parentheses block to avoid escape pitfalls with redirects/&-chars.
(
    echo @echo off
    echo REM PolymarketAutoStart.bat - auto-generated by install-autostart-task.bat
    echo REM Runs at user logon via Startup folder ^(per-user, no UAC^).
    echo REM Sleeps 30s to let network/services come up before bot launch.
    echo timeout /t 30 /nobreak ^> nul
    echo call "%REAL_STARTBAT%"
    echo exit /b 0
) > "%WRAPPER%"

if exist "%WRAPPER%" (
    echo.
    echo SUCCESS: autostart installed.
    echo Wrapper:  %WRAPPER%
    echo Calls:    %REAL_STARTBAT%
    echo.
    echo Verify:   dir "%STARTUP%\PolymarketAutoStart.bat"
    echo Remove:   del "%WRAPPER%"
    echo Test now: call "%WRAPPER%"
    echo.
    type "%WRAPPER%"
) else (
    echo FAILED to write wrapper at %WRAPPER%
    exit /b 1
)

endlocal
